const SCORE_FLOOR = 82;
const GROUP_NAMES = ['出海组', '酒仙组', '财神组', '淘气组'];
const GROUP_STORAGE_KEY = 'xuesheng-random-groups-v1';
const STUDENT_NAMES = [
  '徐娅楠', '谢荣轩', '高炜佳', '钟雪鑫', '吴潇妤', '江超群',
  '杨羽婷', '付萧冉', '刘瑞雪', '崔传钰', '李京阅', '刘羽菲',
  '张隽嘉', '李德嘉', '孟子群', '李恒运', '宋颖涵', '田桓旭',
  '陈一菡', '潘奕竹', '丛芳萱', '王宇成', '刘昊轩', '张津铨',
];

const MODULE_COLORS = {
  m1: 'var(--cyan)',
  m2: 'var(--blue)',
  m3: 'var(--violet)',
  m4: 'var(--amber)',
  m5: 'var(--green)',
  m6: 'var(--teal)',
  m7: 'var(--violet)',
  m8: '#fbbf24',
};

const COURSES = {
  talk: {
    key: 'talk',
    icon: '🎬',
    brandTitle: 'LIVE · AI 课程评价系统',
    brandSubtitle: '直播电商（酒庄方向） · 直播话术课程评价大屏 · 2024-01期',
    screenTitle: '直播话术课',
    projectLabel: '综合直播项目得分',
    summaryTitle: '班级总览',
    summaryTag: '主视图',
    totalLabel: 'TOTAL SCORE',
    aiPanelTitle: 'AI 智能洞察分析',
    aiPanelFooter: '由 AI 自动分析 · 基于直播话术课程8模块数据生成',
    moduleFooterLabels: ['课前 M1', '课堂 M2', '理论 M3', '设计 M4', '实操 M5', '复盘 M6', 'AI M7', '项目 M8'],
    modules: [
      {
        key: 'm1',
        label: 'M1',
        title: '课前学习习惯',
        max: 10,
        color: MODULE_COLORS.m1,
        chartType: 'donut',
        score: 9.0,
        items: [
          { name: '预习完成率', score: 4.5, max: 5 },
          { name: '任务准时率', score: 2.8, max: 3 },
          { name: '话术初稿完整性', score: 1.7, max: 2 },
        ],
      },
      {
        key: 'm2',
        label: 'M2',
        title: '课堂参与表现',
        max: 10,
        color: MODULE_COLORS.m2,
        chartType: 'bar',
        score: 8.8,
        includeModuleTotal: true,
        items: [
          { name: '出勤率', score: 3.8, max: 4 },
          { name: '小组研讨活跃度', score: 2.5, max: 3 },
          { name: '直播演练参与次数', score: 2.5, max: 3 },
        ],
      },
      {
        key: 'm3',
        label: 'M3',
        title: '理论知识掌握',
        max: 15,
        color: MODULE_COLORS.m3,
        chartType: 'radar',
        score: 14.0,
        items: [
          { name: '取信3方法', score: 4.7, max: 5 },
          { name: '促单3效应', score: 4.7, max: 5 },
          { name: 'Yes/And/But逻辑', score: 2.8, max: 3 },
          { name: '话术合规知识', score: 1.8, max: 2 },
        ],
      },
      {
        key: 'm4',
        label: 'M4',
        title: '直播设计能力',
        max: 15,
        color: MODULE_COLORS.m4,
        chartType: 'bar',
        score: 12.5,
        items: [
          { name: '取信话术（专业化/举证/场景化）', score: 6.5, max: 8 },
          { name: '促单话术（心理效应/互动）', score: 6.0, max: 7 },
        ],
      },
      {
        key: 'm5',
        label: 'M5',
        title: '直播实操表现',
        max: 15,
        color: MODULE_COLORS.m5,
        chartType: 'gauge',
        score: 12.5,
        items: [
          { name: '镜头感', score: 3.5, max: 4 },
          { name: '场控稳定性', score: 3.3, max: 4 },
          { name: '突发应对', score: 3.0, max: 4 },
          { name: '流程完整性', score: 2.7, max: 3 },
        ],
      },
      {
        key: 'm6',
        label: 'M6',
        title: '复盘优化能力',
        max: 10,
        color: MODULE_COLORS.m6,
        chartType: 'line',
        score: 7.0,
        trend: [5.0, 6.0, 6.5, 7.0],
        items: [
          { name: '数据反馈使用', score: 3.5, max: 5 },
          { name: '反思改进落实', score: 3.5, max: 5 },
        ],
      },
      {
        key: 'm7',
        label: 'M7',
        title: 'AI 与创新应用',
        max: 15,
        color: MODULE_COLORS.m7,
        chartType: 'bar',
        score: 9.0,
        items: [
          { name: 'DeepSeek优化话术', score: 3.0, max: 5 },
          { name: '数据大屏分析', score: 1.8, max: 3 },
          { name: '数字人PK参与', score: 2.0, max: 3 },
          { name: '文化/双语创新', score: 2.2, max: 4 },
        ],
      },
      {
        key: 'm8',
        label: 'M8',
        title: '综合直播项目成果',
        max: 10,
        color: MODULE_COLORS.m8,
        chartType: 'number',
        score: 9.5,
        items: [
          { name: '完整直播表现（脚本+演练+复盘）', score: 5.7, max: 6 },
          { name: '数据转化指标（观看/互动/下单）', score: 3.8, max: 4 },
        ],
      },
    ],
  },
  ip: {
    key: 'ip',
    icon: '🎭',
    brandTitle: 'LIVE · AI 课程评价系统',
    brandSubtitle: '直播电商（酒庄方向） · IP打造课程评价大屏 · 2024-01期',
    screenTitle: 'IP打造课',
    projectLabel: '综合IP项目得分',
    summaryTitle: '班级总览',
    summaryTag: '主视图',
    totalLabel: 'TOTAL SCORE',
    aiPanelTitle: 'AI 智能洞察分析',
    aiPanelFooter: '由 AI 自动分析 · 基于IP打造课程8模块数据生成',
    moduleFooterLabels: ['课前 M1', '课堂 M2', '理论 M3', '设计 M4', '成果 M5', '复盘 M6', 'AI M7', '项目 M8'],
    modules: [
      {
        key: 'm1',
        label: 'M1',
        title: '课前学习习惯',
        max: 10,
        color: MODULE_COLORS.m1,
        chartType: 'donut',
        score: 9.2,
        items: [
          { name: 'IP概念预习', score: 4.6, max: 5 },
          { name: '任务准时率', score: 2.8, max: 3 },
          { name: 'IP形象初稿完整性', score: 1.8, max: 2 },
        ],
      },
      {
        key: 'm2',
        label: 'M2',
        title: '课堂参与表现',
        max: 10,
        color: MODULE_COLORS.m2,
        chartType: 'bar',
        score: 9.0,
        includeModuleTotal: true,
        items: [
          { name: '出勤率', score: 3.9, max: 4 },
          { name: '小组研讨活跃度', score: 2.6, max: 3 },
          { name: 'IP展示参与', score: 2.5, max: 3 },
        ],
      },
      {
        key: 'm3',
        label: 'M3',
        title: '理论知识掌握',
        max: 15,
        color: MODULE_COLORS.m3,
        chartType: 'radar',
        score: 13.5,
        items: [
          { name: 'IP核心概念', score: 4.5, max: 5 },
          { name: '人设定位方法', score: 4.5, max: 5 },
          { name: '形象要素', score: 2.5, max: 3 },
          { name: '品牌匹配逻辑', score: 2.0, max: 2 },
        ],
      },
      {
        key: 'm4',
        label: 'M4',
        title: 'IP设计能力',
        max: 15,
        color: MODULE_COLORS.m4,
        chartType: 'bar',
        score: 13.0,
        items: [
          { name: '人设定位设计', score: 7.0, max: 8 },
          { name: '形象包装能力', score: 6.0, max: 7 },
        ],
      },
      {
        key: 'm5',
        label: 'M5',
        title: 'IP成果表现',
        max: 15,
        color: MODULE_COLORS.m5,
        chartType: 'gauge',
        score: 13.5,
        items: [
          { name: '形象完整度', score: 3.8, max: 4 },
          { name: '记忆点突出性', score: 3.5, max: 4 },
          { name: '文化契合度', score: 3.2, max: 4 },
          { name: '表达流畅度', score: 3.0, max: 3 },
        ],
      },
      {
        key: 'm6',
        label: 'M6',
        title: '复盘优化能力',
        max: 10,
        color: MODULE_COLORS.m6,
        chartType: 'line',
        score: 8.0,
        trend: [5.8, 6.6, 7.3, 8.0],
        items: [
          { name: '同伴反馈采纳', score: 4.0, max: 5 },
          { name: '形象迭代优化', score: 4.0, max: 5 },
        ],
      },
      {
        key: 'm7',
        label: 'M7',
        title: 'AI 与创新应用',
        max: 15,
        color: MODULE_COLORS.m7,
        chartType: 'bar',
        score: 11.0,
        items: [
          { name: 'DeepSeek辅助人设', score: 4.0, max: 5 },
          { name: 'AI生成视觉素材', score: 2.5, max: 3 },
          { name: '数字人体验', score: 2.5, max: 3 },
          { name: '文化/IP融合创新', score: 2.0, max: 4 },
        ],
      },
      {
        key: 'm8',
        label: 'M8',
        title: '综合IP项目成果',
        max: 10,
        color: MODULE_COLORS.m8,
        chartType: 'number',
        score: 9.3,
        items: [
          { name: 'IP完整方案', score: 5.6, max: 6 },
          { name: '创意与实用性', score: 3.7, max: 4 },
        ],
      },
    ],
  },
  script: {
    key: 'script',
    icon: '📝',
    brandTitle: 'LIVE · AI 课程评价系统',
    brandSubtitle: '直播电商（酒庄方向） · 脚本设计课程评价大屏 · 2024-01期',
    screenTitle: '脚本设计课',
    projectLabel: '综合脚本项目得分',
    summaryTitle: '班级总览',
    summaryTag: '主视图',
    totalLabel: 'TOTAL SCORE',
    aiPanelTitle: 'AI 智能洞察分析',
    aiPanelFooter: '由 AI 自动分析 · 基于脚本设计课程8模块数据生成',
    moduleFooterLabels: ['课前 M1', '课堂 M2', '理论 M3', '设计 M4', '呈现 M5', '复盘 M6', 'AI M7', '项目 M8'],
    modules: [
      {
        key: 'm1',
        label: 'M1',
        title: '课前学习习惯',
        max: 10,
        color: MODULE_COLORS.m1,
        chartType: 'donut',
        score: 8.5,
        items: [
          { name: '脚本模板预习', score: 4.2, max: 5 },
          { name: '任务准时率', score: 2.5, max: 3 },
          { name: '脚本初稿完整性', score: 1.8, max: 2 },
        ],
      },
      {
        key: 'm2',
        label: 'M2',
        title: '课堂参与表现',
        max: 10,
        color: MODULE_COLORS.m2,
        chartType: 'bar',
        score: 8.5,
        includeModuleTotal: true,
        items: [
          { name: '出勤率', score: 3.7, max: 4 },
          { name: '小组脚本研讨', score: 2.5, max: 3 },
          { name: '辩论赛参与', score: 2.3, max: 3 },
        ],
      },
      {
        key: 'm3',
        label: 'M3',
        title: '理论知识掌握',
        max: 15,
        color: MODULE_COLORS.m3,
        chartType: 'radar',
        score: 12.0,
        items: [
          { name: '脚本结构知识', score: 4.0, max: 5 },
          { name: '辩论逻辑知识', score: 4.0, max: 5 },
          { name: '话术节奏与互动', score: 2.2, max: 3 },
          { name: '脚本合规知识', score: 1.8, max: 2 },
        ],
      },
      {
        key: 'm4',
        label: 'M4',
        title: '脚本设计能力',
        max: 15,
        color: MODULE_COLORS.m4,
        chartType: 'bar',
        score: 11.5,
        items: [
          { name: '流程完整性与逻辑性', score: 6.0, max: 8 },
          { name: '辩论论点设计与论据', score: 5.5, max: 7 },
        ],
      },
      {
        key: 'm5',
        label: 'M5',
        title: '脚本呈现表现',
        max: 15,
        color: MODULE_COLORS.m5,
        chartType: 'gauge',
        score: 11.5,
        items: [
          { name: '脚本语言表达力', score: 3.2, max: 4 },
          { name: '辩论反驳与应变', score: 3.0, max: 4 },
          { name: '团队配合', score: 2.8, max: 4 },
          { name: '时间节奏把控', score: 2.5, max: 3 },
        ],
      },
      {
        key: 'm6',
        label: 'M6',
        title: '复盘优化能力',
        max: 10,
        color: MODULE_COLORS.m6,
        chartType: 'line',
        score: 7.5,
        trend: [5.4, 6.3, 6.9, 7.5],
        items: [
          { name: '辩论反馈采纳', score: 3.8, max: 5 },
          { name: '脚本迭代优化', score: 3.7, max: 5 },
        ],
      },
      {
        key: 'm7',
        label: 'M7',
        title: 'AI 与创新应用',
        max: 15,
        color: MODULE_COLORS.m7,
        chartType: 'bar',
        score: 9.5,
        items: [
          { name: 'DeepSeek辅助脚本', score: 3.2, max: 5 },
          { name: 'AI生成话术创意', score: 2.0, max: 3 },
          { name: '数字人演练', score: 2.0, max: 3 },
          { name: '脚本创意亮点', score: 2.3, max: 4 },
        ],
      },
      {
        key: 'm8',
        label: 'M8',
        title: '综合脚本项目成果',
        max: 10,
        color: MODULE_COLORS.m8,
        chartType: 'number',
        score: 8.5,
        items: [
          { name: '完整脚本+辩论表现', score: 5.0, max: 6 },
          { name: '实用性与创意', score: 3.5, max: 4 },
        ],
      },
    ],
  },
  review: {
    key: 'review',
    icon: '📊',
    brandTitle: 'LIVE · AI 课程评价系统',
    brandSubtitle: '直播电商（酒庄方向） · 数据复盘课程评价大屏 · 2024-01期',
    screenTitle: '数据复盘课',
    projectLabel: '综合复盘项目得分',
    summaryTitle: '班级总览',
    summaryTag: '主视图',
    totalLabel: 'TOTAL SCORE',
    aiPanelTitle: 'AI 智能洞察分析',
    aiPanelFooter: '由 AI 自动分析 · 基于数据复盘课程8模块数据生成',
    moduleFooterLabels: ['课前 M1', '课堂 M2', '理论 M3', '分析 M4', '成果 M5', '复盘 M6', 'AI M7', '项目 M8'],
    modules: [
      {
        key: 'm1',
        label: 'M1',
        title: '课前学习习惯',
        max: 10,
        color: MODULE_COLORS.m1,
        chartType: 'donut',
        score: 8.0,
        items: [
          { name: '复盘案例预习', score: 4.0, max: 5 },
          { name: '任务准时率', score: 2.3, max: 3 },
          { name: '数据扒取初稿完整性', score: 1.7, max: 2 },
        ],
      },
      {
        key: 'm2',
        label: 'M2',
        title: '课堂参与表现',
        max: 10,
        color: MODULE_COLORS.m2,
        chartType: 'bar',
        score: 8.0,
        includeModuleTotal: true,
        items: [
          { name: '出勤率', score: 3.6, max: 4 },
          { name: '数据分析讨论', score: 2.3, max: 3 },
          { name: '复盘分享与互评', score: 2.1, max: 3 },
        ],
      },
      {
        key: 'm3',
        label: 'M3',
        title: '理论知识掌握',
        max: 15,
        color: MODULE_COLORS.m3,
        chartType: 'radar',
        score: 10.5,
        items: [
          { name: '核心数据指标', score: 3.5, max: 5 },
          { name: '数据扒取方法', score: 3.5, max: 5 },
          { name: '问题诊断逻辑', score: 2.0, max: 3 },
          { name: '优化方案框架', score: 1.5, max: 2 },
        ],
      },
      {
        key: 'm4',
        label: 'M4',
        title: '数据分析与优化能力',
        max: 15,
        color: MODULE_COLORS.m4,
        chartType: 'bar',
        score: 10.0,
        items: [
          { name: '数据扒取与解读', score: 5.0, max: 8 },
          { name: '优化方案设计', score: 5.0, max: 7 },
        ],
      },
      {
        key: 'm5',
        label: 'M5',
        title: '复盘成果表现',
        max: 15,
        color: MODULE_COLORS.m5,
        chartType: 'gauge',
        score: 10.5,
        items: [
          { name: '数据准确性', score: 3.0, max: 4 },
          { name: '问题诊断深入度', score: 2.8, max: 4 },
          { name: '方案可执行性', score: 2.5, max: 4 },
          { name: '报告呈现质量', score: 2.2, max: 3 },
        ],
      },
      {
        key: 'm6',
        label: 'M6',
        title: '复盘优化能力',
        max: 10,
        color: MODULE_COLORS.m6,
        chartType: 'line',
        score: 7.0,
        trend: [5.0, 5.9, 6.4, 7.0],
        items: [
          { name: '数据反馈循环使用', score: 3.5, max: 5 },
          { name: '方案落地与再复盘', score: 3.5, max: 5 },
        ],
      },
      {
        key: 'm7',
        label: 'M7',
        title: 'AI 与创新应用',
        max: 15,
        color: MODULE_COLORS.m7,
        chartType: 'bar',
        score: 9.0,
        items: [
          { name: 'DeepSeek辅助分析', score: 3.0, max: 5 },
          { name: '数据大屏工具使用', score: 2.0, max: 3 },
          { name: 'AI生成报告', score: 2.0, max: 3 },
          { name: '复盘创新方法', score: 2.0, max: 4 },
        ],
      },
      {
        key: 'm8',
        label: 'M8',
        title: '综合复盘项目成果',
        max: 10,
        color: MODULE_COLORS.m8,
        chartType: 'number',
        score: 7.0,
        items: [
          { name: '完整复盘报告', score: 4.2, max: 6 },
          { name: '优化方案质量', score: 2.8, max: 4 },
        ],
      },
    ],
  },
};

window.DASHBOARD_CONSTANTS = {
  SCORE_FLOOR,
  GROUP_NAMES,
  GROUP_STORAGE_KEY,
  STUDENT_NAMES,
  MODULE_COLORS,
  COURSES,
};
